mysql_default: &mysql_default
  adapter: mysql
  encoding: utf8
  username: root
  host: localhost
  password: passw0rd
  socket: /tmp/mysql.sock
  pool: 5
  timeout: 5000

development:
  <<: *mysql_default
  database: salta_development

test:
  <<: *mysql_default
  database: salta_test

production:
  <<: *mysql_default
  database: salta_development


